{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "2.0"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-2.0.jar",
          "url": "aabresguard-plugin-2.0.jar",
          "size": 19904,
          "sha512": "871deb3cde921e158eb001e76d4ae8e84ddd7253d4d843a6939a8db5c60e022c324e757950958adb63798c1196deb7a43f56e13d4da8b71493a045fdfc87e24d",
          "sha256": "c6f4e8d1f3a4e41d87e2f152851649a7da3630980c33e2bdc3e71243b6a8dc4e",
          "sha1": "ba2ef69c095faf25db41692e5f014a44cca54973",
          "md5": "78d5d35602852f4b816f84adbfcebdde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "2.0"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-2.0.jar",
          "url": "aabresguard-plugin-2.0.jar",
          "size": 19904,
          "sha512": "871deb3cde921e158eb001e76d4ae8e84ddd7253d4d843a6939a8db5c60e022c324e757950958adb63798c1196deb7a43f56e13d4da8b71493a045fdfc87e24d",
          "sha256": "c6f4e8d1f3a4e41d87e2f152851649a7da3630980c33e2bdc3e71243b6a8dc4e",
          "sha1": "ba2ef69c095faf25db41692e5f014a44cca54973",
          "md5": "78d5d35602852f4b816f84adbfcebdde"
        }
      ]
    }
  ]
}
