def versions = [:]
versions.agp = "9.2.1"
versions.kotlin = "2.3.21"
versions.java = "21"
versions.aabresguard = "2.1"
// android
versions.compileSdkVersion = 35
versions.minSdkVersion = 21
versions.targetSdkVersion = 35
versions.support = "28.0.0"

versions.bundletool = "1.18.3"

versions["aabresguard-core"] = versions.aabresguard
versions["aabresguard-plugin"] = versions.aabresguard

// plugin
//versions["bintray-plugin"] = "1.8.4"
versions.shadow = "9.4.1"

ext.versions = versions

ext.deps = [:]

// gradle
def gradle = [:]
gradle.agp = "com.android.tools.build:gradle:${versions.agp}"
deps.gradle = gradle
// kotlin
def kotlin = [:]
kotlin.stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$versions.kotlin"
kotlin.plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
kotlin.allopen = "org.jetbrains.kotlin:kotlin-allopen:$versions.kotlin"
kotlin.embeddable = "org.jetbrains.kotlin:kotlin-compiler-embeddable:$versions.kotlin"
deps.kotlin = kotlin
// plugin
def plugin = [:]
plugin.shadow = "com.gradleup.shadow:shadow-gradle-plugin:${versions.shadow}"
//plugin['bintray-plugin'] = "com.jfrog.bintray.gradle:gradle-bintray-plugin:${versions["bintray-plugin"]}"
deps.plugin = plugin
// library
deps.appcompat = "androidx.appcompat:appcompat:1.7.0"
deps.bundletool = "com.android.tools.build:bundletool:${versions.bundletool}"
// aabresguard
def aabresguard = [:]
aabresguard.core = "$GROUP_ID:aabresguard-core:${versions["aabresguard"]}"
aabresguard.plugin = "$GROUP_ID:aabresguard-plugin:${versions["aabresguard"]}"
deps.aabresguard = aabresguard

ext.deps = deps